# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

In [8]:
import numpy as np
array= np.arange(1,11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

In [22]:
array2 = np.zeros((3,3), dtype = int)
array2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

In [24]:
c = np.linspace(0,5,10, endpoint = False)
c

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

In [11]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

In [12]:
a = np.random.random((4,4))
a

array([[0.59367291, 0.00968688, 0.0536474 , 0.28796739],
       [0.12482704, 0.52917464, 0.17356546, 0.37995449],
       [0.0611606 , 0.76442176, 0.79831774, 0.13373638],
       [0.37173006, 0.54289453, 0.60766857, 0.97431189]])

In [27]:
np.random.seed(10)
a = np.random.random((4,4))
a

array([[0.77132064, 0.02075195, 0.63364823, 0.74880388],
       [0.49850701, 0.22479665, 0.19806286, 0.76053071],
       [0.16911084, 0.08833981, 0.68535982, 0.95339335],
       [0.00394827, 0.51219226, 0.81262096, 0.61252607]])

In [28]:
np.random.seed(0)
a = np.random.random((4,4))
a

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

---

### Exercise 6:
Find the shape of a NumPy array.

In [13]:
print(a.shape) 

(4, 4)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

In [14]:
f = np.arange(16).reshape((4,4))
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

In [16]:
print(f.dtype)

int32


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

In [23]:
c=np.arange(1,101)
c1= c[1::2]
# c1=[k for k in c if k%2==0]
c1

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

In [19]:
x = np.random.randint(10,50, size=(6,6))
x

array([[46, 33, 43, 20, 11, 30],
       [12, 48, 36, 11, 29, 25],
       [37, 33, 38, 38, 38, 34],
       [44, 12, 39, 27, 49, 33],
       [29, 33, 40, 48, 15, 23],
       [10, 13, 43, 35, 38, 28]])

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

In [25]:
y = np.random.randint(10, size=(3, 4))
s= y[:2, 1:3]
s

array([[7, 0],
       [9, 7]])

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

In [26]:
f = np.arange(16).reshape((4,4))
np.sum(f)

120

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

In [32]:
A = np.arange(16).reshape((4,4))
print("The mean is:", np.mean(A), "The median:", np.median(A), "The standdard deviation:", np.std(A))

The mean is: 7.5 The median: 7.5 The standdard deviation: 4.6097722286464435


---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

In [33]:
c=np.arange(1,101)
print("The maximum value is:", np.max(c), " and the minimum is:", np.min(c))

The maximum value is: 100  and the minimum is: 1


---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

In [99]:
np.random.seed(8102024)
n20 = np.random.randint(10,size = 20)
m = np.max(n20)
index = np.where(n20 == m);
print("The index of the maximum value is:", index)


The index of the maximum value is: (array([ 7, 14, 17], dtype=int64),)


In [100]:
m=np.argmax(n20)
print(m)

7


---

### Exercise 16:
Create a NumPy array and reverse its elements.

In [51]:
X = np.arange(10)
Z = np.flip(X)

Z

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

In [53]:
A = np.arange(9).reshape((3,3))
B = np.arange(9,18).reshape((3,3))
m= np.multiply(A, B)
print(m)

[[  0  10  22]
 [ 36  52  70]
 [ 90 112 136]]


---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

In [54]:
D1= np.arange(9)
D = np.diag(D1)
D

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8]])

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

In [55]:
A = np.arange(9).reshape((3,3))
B = np.arange(9,18).reshape((3,3))
print(np.dot(A,B))

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


In [93]:
A = np.arange(9).reshape((3,3))
B = np.arange(9,18).reshape((3,3))
print(A.dot(B))

[[ 42  45  48]
 [150 162 174]
 [258 279 300]]


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

In [59]:
A = np.arange(9).reshape((3,3))
W = A.ravel()
W

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

---

### Exercise 21:
Stack two NumPy arrays vertically.

In [62]:
A = np.arange(9).reshape((3,3))
B = np.arange(9,18).reshape((3,3))
C= np.vstack((A,B))
C

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

---

### Exercise 22:
Stack two NumPy arrays horizontally.

In [63]:
A = np.arange(9).reshape((3,3))
B = np.arange(9,18).reshape((3,3))
C= np.hstack((A,B))
C

array([[ 0,  1,  2,  9, 10, 11],
       [ 3,  4,  5, 12, 13, 14],
       [ 6,  7,  8, 15, 16, 17]])

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

In [65]:
A = np.arange(9).reshape((3,3))
B = np.arange(9,18).reshape((3,3))
C= np.hstack((A,B))
print(np.split(C,3)) # 3 equal sized subarrays

[array([[ 0,  1,  2,  9, 10, 11]]), array([[ 3,  4,  5, 12, 13, 14]]), array([[ 6,  7,  8, 15, 16, 17]])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

In [66]:
v=np.random.random((4,4))
v

array([[0.84150463, 0.98888176, 0.08490676, 0.53549355],
       [0.90010679, 0.91097961, 0.59591404, 0.96887406],
       [0.41811546, 0.35410523, 0.94077555, 0.3806912 ],
       [0.58671376, 0.8458463 , 0.10862643, 0.26214823]])

In [69]:
V=np.around(v, decimals = 2)
V

array([[0.84, 0.99, 0.08, 0.54],
       [0.9 , 0.91, 0.6 , 0.97],
       [0.42, 0.35, 0.94, 0.38],
       [0.59, 0.85, 0.11, 0.26]])

---

### Exercise 25:
Find the unique elements of a NumPy array.

In [72]:
C = np.ones((3,4), dtype = int)
C

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [73]:
print(np.unique(C))

[1]


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

In [74]:
V=np.around(v, decimals = 2)
V

array([[0.84, 0.99, 0.08, 0.54],
       [0.9 , 0.91, 0.6 , 0.97],
       [0.42, 0.35, 0.94, 0.38],
       [0.59, 0.85, 0.11, 0.26]])

In [76]:
Replaced = np.where(V < 0.2, 0.2, V )
Replaced

array([[0.84, 0.99, 0.2 , 0.54],
       [0.9 , 0.91, 0.6 , 0.97],
       [0.42, 0.35, 0.94, 0.38],
       [0.59, 0.85, 0.2 , 0.26]])

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

In [78]:
A = np.arange(9)
print(np.cumsum(A))

[ 0  1  3  6 10 15 21 28 36]


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

In [79]:
A = np.arange(9).reshape((3,3))
np.count_nonzero(A)

8

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

In [80]:
n20 = np.random.randint(10,size = 20)
n20

array([3, 7, 2, 5, 7, 4, 8, 8, 7, 3, 6, 4, 3, 5, 8, 3, 0, 1, 3, 4])

In [84]:
print(np.sort(n20))

[0 1 2 3 3 3 3 3 4 4 4 5 5 6 7 7 7 8 8 8]


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

In [85]:
mat = np.arange(16).reshape((4,4))
np.sum(mat, axis=0)   ### column-wise
 

array([24, 28, 32, 36])

In [86]:

np.sum(mat, axis=1)   ### row-wise 

array([ 6, 22, 38, 54])

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

In [90]:
mat = np.random.randint(16, size = ((4,4)))
mat


array([[ 6, 15, 15,  4],
       [12, 10, 10,  4],
       [15, 10,  7,  5],
       [ 9, 10, 15, 14]])

In [91]:
matNorm = (mat-np.min(mat))/(np.max(mat)-np.min(mat))
matNorm

array([[0.18181818, 1.        , 1.        , 0.        ],
       [0.72727273, 0.54545455, 0.54545455, 0.        ],
       [1.        , 0.54545455, 0.27272727, 0.09090909],
       [0.45454545, 0.54545455, 1.        , 0.90909091]])

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

In [95]:
A = np.arange(9)
B = np.arange(9,18)
print(A.dot(B))

528


---

### Exercise 33:
Find the trace of a square NumPy matrix.

In [96]:
A = np.arange(9).reshape((3,3))
print(np.trace(A))

12


---

### Exercise 34:
Create a 2D array and swap two rows.

In [97]:
A = np.arange(9).reshape((3,3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
A = A[[1,0,2]] # Swapping the first and second rows
A

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

In [101]:
U = np.arange(16)
U=U.reshape(-1,1)
U

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

In [105]:
A = np.arange(9,18).reshape((3,3))
print(np.linalg.det(A))

4.996003610813198e-15


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

In [106]:
Q = np.arange(9,13).reshape((2,2))
print(np.linalg.eig(Q))

(array([-0.09481005, 21.09481005]), array([[-0.73979641, -0.63720844],
       [ 0.67283079, -0.77069151]]))


---

### Exercise 38:
Solve a system of linear equations using NumPy.

In [108]:
A = np.arange(9,18).reshape((3,3))
b =np.arange(6,9)
print(A)
print(b)

[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[6 7 8]


In [109]:
x = np.linalg.solve(A, b)
print(x)

[-1.89478063e-15 -2.33333333e+00  2.66666667e+00]


---

### Exercise 39:
Add Gaussian noise to a NumPy array.

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

In [111]:
v4 = np.arange(1,17).reshape((4,4))
print(np.diag(v4))

[ 1  6 11 16]


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.